### PR TITLE
Display descriptor

### PR DESCRIPTION
**Pull request by rpavlik**
This is the work @DuFF14 has done on addressing #6

### CODE REVIEW

**Comment by rpavlik** [comment]
Quoting @DuFF14:
> Display descriptor example: https://github.com/OSVR/OSVR-Core/blob/DisplayConfigs/apps/displays/HMD.json
>
> Some questions/comments:
> 1) Any reason to keep everything wrapped in the top level "hmd" object (not included in this draft)? What other types of displays should be described in this schema?
>
> 2) In this draft, "resolutions" is of type "object" rather than "array". The Unity plugin is set up to handle one resolution. An HMD that supports multiple resolutions requires multiple display descriptors. Would change to "resolution" and type "object" if there will only be one per display descriptor.
>
> 3) Same for "eyes". It is an array in our current examples, but there is only ever one entry in the examples I've seen. centerProjX, centerProjY, rotate180 is applied to both eyes. Are there instances where these values differ per eye? If so, should this always be an array of size two? (Or an object properties that specify left/right?) If not, I would change this to type "object" instead of "array".

**Comment by DuFF14** [comment]
Added a meta field with version number. We will still need some more information about eyes. Distance to screen, lens properties?

**Comment by rpavlik** [comment]
Can I close this one out? I've put in the v1 schema based on this work, with some fixes, etc. The overall display model re-architecting probably deserves its own issue somewhere else, and the schema for a descriptor will fall out of that.

**Comment by DuFF14** [comment]
Yes, this can be closed now.

**Pull request closed without merging**
